#!/bin/bash
# Hal Pomeranz (hrpomeranz@gmail.com) - 2026-06-24
#
# strings -a -t d /some/image/file >strings.txt
# byte2fsblock /some/image/file strings.txt >strings-with-filenames.txt

DEVICE=$1
INPUTFILE=$2

XFS_DB=/usr/local/sbin/xfs_db

(echo blockget -n -s -L
 cat "$INPUTFILE" | while read byte string; do
     sector=$(($byte / 512))
     fsblock=$($XFS_DB -r $DEVICE -c "convert daddr $sector fsblock" | cut -f1 -d' ')

     echo fsblock $fsblock
     echo blockuse -n
 done) |
    $XFS_DB -r $DEVICE |
    sed 's/^.*xfs_db> block //; s/ (.*) type//; s/data inode //;' |
    paste - "$INPUTFILE"
